### ISSUE TITLE
FixedTotalNum as subclass of FixedNum maybe better?

### ISSUE THREAD

**Issue by joyeewang** [brainpy/BrainPy#301]
class FixedTotalNum(TwoEndConnector):
  """Connect the synaptic neurons with fixed total number.
  Parameters
  ----------
  num : float,int
    The conn total number.
  seed: int, optional
    The random number seed.
  """

I think FixedTotalNum also needs to support allow_multi_conn, include_sel, so as subclass of FixedNum maybe a better fit?

**Comment by chaoming0625** [comment]
See #434
