### ISSUE TITLE
``DynamicalSystem`` as a function

### ISSUE THREAD

**Issue by chaoming0625** [brainpy/BrainPy#332]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

Currently, a ``DynamicalSystem`` should define ``update`` function which receive two arguments: 

- ``s``: shared arguments
- ``x``: individual inputs

However, it is possible to call a ``DynamicalSystem`` as a function. Because shared arguments can be got through a global function like ``brainpy.math.get_current_step_data()``.

At each step, data for the next time step can be set through:

```
brainpy.math.set_current_step_data()
```

**Comment by chaoming0625** [comment]
Through this way, there is no need to pass shared arguments ``s`` into the submodule. And new models in BrainPy can be called like a function. How do you think? @ztqakita

**Comment by ztqakita** [comment]
In my opinion, models in BrainPy can be called like a function by passing shared argument `s` and input `x`, why bother changing the update function?

**Comment by ztqakita** [comment]
However, I agree that we can use another way to deal with shared arguments `s` instead of treating them as `update` function arguments.
