### ISSUE TITLE
ImportError and circular dependency issue when running a decision-making network simulation

### ISSUE THREAD

**Issue by Airs702** [brainpy/BrainPy#362]
Environment:

Operating System: Windows
Python version: 3.10
BrainPy version: 2.4.0

Issue description:

I encountered import errors and circular dependency issues when trying to run the decision-making network simulation example provided on the BrainPy website. The initial issue was with the numba_range function not being correctly imported. I managed to fix this issue by copying the complete definition of numba_util.py from brainpy/tools/others to brainpy/tools. However, after this change, I encountered a circular dependency issue involving the brainpy.types.Shape class.

Affected file:

The problematic file is brainpy/_src/connect/random_conn.py. The circular dependency issue arises in this file.

Error messages/tracebacks:

ImportError: cannot import name 'Shape' from partially initialized module 'brainpy.types' (most likely due to a circular import) (C:\Users\Airs\miniconda3\envs\py\lib\site-packages\brainpy\types.py)

Additional information:

I followed the instructions provided on the BrainPy website to set up the environment and run the simulation. However, I encountered the aforementioned issues. I would like to confirm whether this is a problem with the library or if there is a mistake in my installation process.

**Comment by chaoming0625** [comment]
Hi, I tried the code in [decision making code](https://github.com/brainpy/examples/blob/main/decision_making/Wang_2002_decision_making_spiking.py), and I found it still works. Can you uninstall brainpy first, and then reinstall brainpy:

```bash

>>> pip uninstall brainpy
>>> pip install brainpy

```

Please tell me whether it is still failed. Thanks.

**Comment by Airs702** [comment]
Thank you, after reinstalling BrainPy, the code indeed works now. I'm sorry for the trouble.
