### ISSUE TITLE
How to properly disable jit for debugging?

### ISSUE THREAD

**Issue by CloudyDory** [brainpy/BrainPy#447]
- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:
- [x] If applicable, include full error messages/tracebacks.

The Brainpy's FAQ says we should disable jit when debugging, but I am not sure how to use `jax.disable_jit()` in actual code. 

For example, in the following code of a Hodgkin-Huxley model, I hope to inspect the value of `alpha_n` in function `dn(self, n, t, V)` by inserting `print(alpha_n)`. However, the printed information is still `Traced<ShapedArray(float32[1])>with<DynamicJaxprTrace(level=1/0)>`, which is just the same as the output without using `jax.disable_jit()`. Note that in this code, I also try to globally disable jit in the first two lines, but it still doesn't work.

Hope someone can help me with this. Thanks!

```python
from jax.config import config
config.update('jax_disable_jit', True)

import jax
import brainpy as bp
import brainpy.math as bm
from brainpy.channels import INa_HH1952, IL

print(bp.__version__)
bm.set_platform('cpu')

class IK(bp.dyn.IonChannel):  # bp.Channel
    def __init__(self, size, E=-77., g_max=36., phi=1., method='rk4'):  # 'exp_auto'
        super(IK, self).__init__(size)
        self.g_max = g_max
        self.E = E
        self.phi = phi
      
        self.n = bm.Variable(bm.zeros(size))  # variables should be packed with bm.Variable
        
        self.integral = bp.odeint(self.dn, method=method)
    
    def dn(self, n, t, V):
        alpha_n = 0.01 * (V + 55) / (1 - bm.exp(-(V + 55) / 10))
        print(alpha_n)
        beta_n = 0.125 * bm.exp(-(V + 65) / 80)
        return self.phi * (alpha_n * (1. - n) - beta_n * n)
    
    def update(self, tdi, V):
        self.n.value = self.integral(self.n, tdi.t, V, dt=tdi.dt)
    
    def current(self, V):
        return self.g_max * self.n ** 4 * (self.E - V)

class HH(bp.dyn.CondNeuGroup):  # bp.CondNeuGroup
    def __init__(self, size):
        super().__init__(size, V_initializer=bp.init.Uniform(-70, -50.))
        self.IK = IK(size, E=-77., g_max=36.)
        self.INa = INa_HH1952(size, E=50., g_max=120.)
        self.IL = IL(size, E=-54.39, g_max=0.03)

with jax.disable_jit():      
    neu = HH(size=1)
    
    runner = bp.DSRunner(
        neu, 
        monitors=['V'], 
        inputs=('input', 6.)  # constant external inputs of 6 mA to all neurons
    )
    
    runner.run(200)  # the running time is 200 ms
```

**Comment by chaoming0625** [comment]
Great. I think the documentation should be updated. 

For debugging using ``brainpy.DSRunner`` or ``brainpy.math.for_loop``, we should use:

- ```brainpy.DSRunner(..., jit=False)```
- ```brainpy.for_loop(..., jit=False)```

This will solve this issue.

**Comment by CloudyDory** [comment]
Thank you, the solution works!

**Comment by chaoming0625** [comment]
The corresponding doc has been updated. 

- https://brainpy.readthedocs.io/en/latest/tutorial_FAQs/how_to_debug.html
