### ISSUE TITLE
Suggestion to clean up redundant module names in Brainpy

### ISSUE THREAD

**Issue by CloudyDory** [brainpy/BrainPy#463]
Hi, thanks for your time and effort in developing Brainpy. It's a great tool to use.

However, when reading the [brainpy examples](https://github.com/brainpy/examples), I found different tutorial files use different module names, which actually refer to the same underlying module, and this can easily confuse newcomers when learning Brainpy.

For example:

- In "Implementation 1" of [ei_nets/Brette_2007_COBAHH.ipynb](https://github.com/brainpy/examples/blob/main/ei_nets/Brette_2007_COBAHH.ipynb), the neurons are inherited from `bp.NeuGroup`. 
- In "Old version" of [ei_nets/Tian_2020_EI_net_for_fast_response.ipynb](https://github.com/brainpy/examples/blob/main/ei_nets/Tian_2020_EI_net_for_fast_response.ipynb), the neurons are inherited from  `bp.dyn.NeuDyn`.
- In ["Customizing Your Neuron Models"](https://brainpy.readthedocs.io/en/latest/tutorial_building/customize_neuron_models.html),  we can also construct neuron models by inheriting from `bp.dyn.NeuGroup`.

And actually, `bp.NeuGroup`, `bp.dyn.NeuDyn`, and `bp.dyn.NeuGroup` all refer to `brainpy._src.dyn.base.NeuDyn`, so if I understand correctly, the three are completely the same. If this is true, I suggest keeping only one and using it consistently throughout the tutorials.

Another example is `bp.Network` and `bp.DynSysGroup`, which both refer to `brainpy._src.dynsys.DynSysGroup`. The two names look very different, so I also suggest to keep only one.

**Comment by chaoming0625** [comment]
Thanks for raising this question. This is indeed a problem. However, we have always been busy. I hope there are contributors who can help us fix and improve these issues.

**Comment by ztqakita** [comment]
Great suggestion! I will clean up the example docs to the latest version as soon as possible.
