### ISSUE TITLE
Inconsistent "include_self" flag in "brainpy._src.dynold.synapses._TwoEndConnAlignPre" and "brainpy._src.dnn.linear.AllToAll"

### ISSUE THREAD

**Issue by CloudyDory** [brainpy/BrainPy#466]
- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

When passing `brainpy.conn.All2All(include_self=False)` into `brainpy.synapses.AMPA` class, the `include_self=False` flag seems to be silently ignored.

Running the following code:
```python
import brainpy as bp

E = bp.neurons.HH(size=4)
Synapse = bp.synapses.AMPA(E, E, bp.conn.All2All(include_self=False))

print(Synapse.conn.include_self)
print(Synapse.comm.include_self)
```

outputs:
```
False
True
```

And it seems that when computing the synaptic current, setting `include_self` to `True` or `False` makes no difference.

**Comment by chaoming0625** [comment]
Thank you for your report. This is a bug. 

The error is caused by the following line, which does not initialize an ``AllToAll`` connection. 

https://github.com/brainpy/BrainPy/blob/0277bd53b875985f9fc217bf247a21c257271b74/brainpy/_src/dynold/synapses/base.py#L306
