### ISSUE TITLE
Support for physical quantities

### ISSUE THREAD

**Issue by chaoming0625** [brainpy/BrainPy#512]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

A quantity is the pairing of a number and a unit of measure that indicates the amount of some measurable thing. BrainPy should provide quantity objects that keep the units with the number, making it easy to share them as single object.

**Comment by Routhleck** [comment]
See [brainunit](https://github.com/chaobrain/brainunit)
