### ISSUE TITLE
CPU and GPU operator customization based on Taichi

### ISSUE THREAD

**Issue by chaoming0625** [brainpy/BrainPy#518]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

See https://github.com/taichi-dev/taichi/issues/6367

**Comment by Routhleck** [comment]
Expose the `import_cpu_memory` and `import_cuda_memory` C API so that taichi's NdArray can directly use the memory address allocated by XLA to eliminate the memory copy consumption. https://github.com/taichi-dev/taichi/pull/8368

**Comment by chaoming0625** [comment]
Does the CUDA backend also work now?

**Comment by Routhleck** [comment]
YES, I just tested it on CUDA backend and the results are correct!

**Comment by chaoming0625** [comment]
See #527

**Comment by chaoming0625** [comment]
See https://github.com/brainpy/BrainPy/pull/553
