### ISSUE TITLE
Operator customization with Taichi JIT mode

### ISSUE THREAD

**Issue by chaoming0625** [brainpy/BrainPy#570]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

BrainPy currently supports operator customization with the Taichi AOT interface (see #518 #553 ). However, many features of Taichi are not supported in taichi AOT, for example, the compatibility with macOS, and other advanced features. Therefore, it is urgent to support JIT mode-based Taichi operator customization.

**Comment by Routhleck** [comment]
See [braintaichi](https://github.com/chaobrain/braintaichi)
