### ISSUE TITLE
softplus is not correct

### ISSUE THREAD

**Issue by Dr-Chen-Xiaoyu** [brainpy/BrainPy#580]
Hi, brainpy team:

Based on the source code (https://brainpy.readthedocs.io/en/latest/_modules/brainpy/_src/math/activations.html#softplus):
```python
def softplus(x, beta=1, threshold=20):
  x = x.value if isinstance(x, Array) else x
  return jnp.where(x > threshold, x * beta, 1 / beta * jnp.logaddexp(beta * x, 0))
```
The softplus activation in brainpy is not correct in the reverted linear part, whose slop should always be 1. The behavior can be replicated with codes:
```python
import matplotlib.pyplot as plt
import brainpy as bp
import brainpy.math as bm
softplus=bp.dnn.Softplus(beta=0.1) # try different beta
scale = 5e1
x=bm.linspace(-scale,scale,20001)
plt.plot(x,softplus(x))
```
![image](https://github.com/brainpy/BrainPy/assets/129139452/f0801946-8533-4ee8-b1e7-b900538bddd1)      

Based on equation of softplus (https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) and usage of threshold (https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html#torch.nn.Softplus), It might be corrected by this:
```python
def softplus(x, beta=1, threshold=20):
  x = x.value if isinstance(x, Array) else x
  return jnp.where( x > threshold/beta , x, 1 / beta * jnp.logaddexp(beta * x, 0))
```
or might just directly use jax's softplus, if it can be auto-graded by brainpy:
```python
def softplus(x, beta=1):
  return jax.nn.softplus(beta*x)/beta
```

Best,
XiaoyuChen, SJTU

**Comment by chaoming0625** [comment]
Thanks for the report~

**Comment by chaoming0625** [comment]
Please see #581. 

Moreover, I have increased the default threshold to 40. 

Currently the softplus function is:

![Figure_1](https://github.com/brainpy/BrainPy/assets/14275596/fed1607f-8fef-41ad-9eb4-480a71d6adbe)
