### ISSUE TITLE
Questions on the definition of .update() function

### ISSUE THREAD

**Issue by hongruj** [brainpy/BrainPy#594]
Hi, I am a beginner at BrainPy and impressed by its powerful framework. However, I have difficulty in understanding the defination of `.update()` function in SNN. Could you please give some advice?

Firstly, in the tutorial of [Train a SNN model](https://brainpy.readthedocs.io/en/latest/tutorial_training/bp_training.html#train-a-snn-model), the code of `.update()` is as follows:
```
classSNNModel(bp.DynamicalSystem):
  def __init__(self, num_in, num_rec, num_out):
    super(SNNModel, self).__init__()

    # parameters
    self.num_in = num_in
    self.num_rec = num_rec
    self.num_out = num_out

    # neuron groups
    self.r = bp.dyn.LifRef(num_rec, tau=10, V_reset=0, V_rest=0, V_th=1.)
    self.o = bp.dyn.Leaky(num_out, tau=5)

    # synapse: i->r
    self.i2r = bp.dyn.HalfProjAlignPost(comm=bp.dnn.Linear(num_in, num_rec, bp.init.KaimingNormal(scale=2.)),
                                        syn=bp.dyn.Expon(num_rec, tau=10.),
                                        out=bp.dyn.CUBA(),
                                        post=self.r)
    # synapse: r->o
    self.r2o = bp.dyn.HalfProjAlignPost(comm=bp.dnn.Linear(num_rec, num_out, bp.init.KaimingNormal(scale=2.)),
                                        syn=bp.dyn.Expon(num_out, tau=10.),
                                        out=bp.dyn.CUBA(),
                                        post=self.o)

  def update(self, spike):
    self.i2r(spike)
    self.r2o(self.r.spike.value)
    self.r()
    self.o()
    return self.o.x.value
```

The input (spike) has been passed through `self.i2r` and `self.r2o` to the output (`self.o`). Could we define `update()` without `self.r()` and `self.o()` as: 

```
def update(self, spike):
    self.i2r(spike)
    self.r2o(self.r.spike.value)
    return self.o.x.value
```

Secondly, how to get the value of the current running index i? For example, 
```
def update(self, spike):
    self.i2r(spike)
    self.r2o(self.r.spike.value)
    self.r()
    self.o()
    i = bp.share.load('i').  # how to get an int object like i=0 for the first step
    if i>25:
        a = self.o.x.value
    else:
        a = 0 * self.o.x.value
    return a
```

Thanks for your help.

**Comment by ztqakita** [comment]
Thanks for using BrainPy! The first question

**Comment by ztqakita** [comment]
Thanks for using BrainPy!
- The first question: `self.r()` and `self.o()` will update two neuron groups at the current step, which involves the integration of membrane potential `V`. `self.i2r()` and `self.r2o()` will only update the synapse states. In `update()` function, you need to pass the input spikes and recurrent spikes because the synapse model is defined as `HalfProjAlignPost`. Also the update order in `update` function is recommended as synapses first and neurons then. 
- The second question: Exactly! you can use `i = bp.share.load('i')` to get the value of the current running index i.

**Comment by hongruj** [comment]
Thanks for your explanation!

For the second question, i = bp.share.load('I') seems to fail to get the value. when I tried to print i, I got: 
Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=2/0)>
Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=1/0)>

And in the mentioned codes 
```
def update(self, spike):
    self.i2r(spike)
    self.r2o(self.r.spike.value)
    self.r()
    self.o()
    i = bp.share.load('i').  # how to get an int object like i=0 for the first step
    if i>25:
        a = self.o.x.value
    else:
        a = 0 * self.o.x.value
    return a
```
`if I >25:`reports an error. _TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[]..This concrete value was not available in Python because it depends on the value of the argument x[0]._



Another question is the use of `self.r()` and `self.r.spike` in the `.update()`. I only know  `self.r()` is Array, while `self.r.spike` is Variable, and they have the same value.  How to use them correctly in the function? In this example code:
```
class SNN(bp.DynSysGroup):
  def __init__(self, num_in, num_rec, num_out, scale=10.):
    super(SNN, self).__init__()

    # parameters
    self.num_in = num_in
    self.num_rec = num_rec
    self.num_out = num_out
    # recurrent: r
    self.r = bp.dyn.Lif(num_rec, tau=10, V_reset=0, V_rest=0, V_th=1.)
    # synapse: i->r
    self.i2r = Exponential(num_in, self.r, scale=scale)
    # synapse: r->r
    self.r2r = Exponential(num_rec, self.r, scale=scale)
    # output: o
    self.readout = bp.Sequential(
      bp.dnn.Linear(num_rec, num_out, W_initializer=bp.init.KaimingNormal(scale=20.)),
      bp.dyn.Expon(num_out, tau=10.),
      bp.dyn.Leaky(num_out, tau=5)
    )

  def update(self, spike):
    self.i2r(spike)
    self.r2r(self.r.spike)
    return self.readout(self.r())
```
when I changed the last line into `return self.readout(self.r.spike)`, all of the membrane and spikes of the r as well as output are zero. 

thanks you so much!

**Comment by chaoming0625** [comment]
Since ``i`` has been JIT traced, you should not use ``if ... else ...`` to write the code. Rather, using ``brainpy.math.ifelse``, or ``brainpy.math.cond`` if the ``Variable`` are used in the condition branches. Otherwise, using ``jax.lax.cond``,  ``bm.where`` for selection. 

```python

def update(self, spike):
    self.i2r(spike)
    self.r2o(self.r.spike.value)
    self.r()
    self.o()
    i = bp.share.load('i').  # how to get an int object like i=0 for the first step
    a = bm.where(i > 25,  self.o.x.value, 0)
    return a

```

**Comment by chaoming0625** [comment]
This is also correct. 


```python

class SNN(bp.DynSysGroup):
  def __init__(self, num_in, num_rec, num_out, scale=10.):
    super(SNN, self).__init__()

    # parameters
    self.num_in = num_in
    self.num_rec = num_rec
    self.num_out = num_out
    # recurrent: r
    self.r = bp.dyn.Lif(num_rec, tau=10, V_reset=0, V_rest=0, V_th=1.)
    # synapse: i->r
    self.i2r = Exponential(num_in, self.r, scale=scale)
    # synapse: r->r
    self.r2r = Exponential(num_rec, self.r, scale=scale)
    # output: o
    self.readout = bp.Sequential(
      bp.dnn.Linear(num_rec, num_out, W_initializer=bp.init.KaimingNormal(scale=20.)),
      bp.dyn.Expon(num_out, tau=10.),
      bp.dyn.Leaky(num_out, tau=5)
    )

  def update(self, spike):
    self.i2r(spike)
    self.r2r(self.r.spike)
    self.r()  # update this neuronal dynamics first
    return self.readout(self.r.spike.value)
```

**Comment by chaoming0625** [comment]
我们也可以用中文交流。

**Comment by hongruj** [comment]
我明白啦，非常感谢｡◕◡◕｡)ﾉ
