### ISSUE TITLE
Reopen issue #599 (memory issue)

### ISSUE THREAD

**Issue by PikaPei** [brainpy/BrainPy#611]
Hello,
I commented earlier on a different issue but couldn't reopen it, so I'm opening this one. Thank you.
https://github.com/brainpy/BrainPy/issues/599#issuecomment-1918451756

**Comment by chaoming0625** [comment]
Thanks for opening this question. I also have no idea. Please do not assign any reference to Python variables if you do not need it. Make it an intermediate value and only return the needed analysis values.

**Comment by chaoming0625** [comment]
It seems that JAX has some strange memory leak issue. Please also see https://github.com/google/jax/issues/11448, https://github.com/google/jax/issues/12719 .

**Comment by PikaPei** [comment]
Understood, thanks for your reply. I will now close this issue.
