### ISSUE TITLE
Deprecated collections type

### ISSUE THREAD

**Issue by KafCoppelia** [brainpy/BrainPy#676]
`collections.Iterable` this usage is deprecated in py3.10 and later, use `collections.abc.Iterable` instead.

```python
import brainpy as bp
hh = bp.neurons.HH((10, 20), keep_size=True)
hh2 = hh[None, 1:]
```

If the wrong slice is passed in, an exception will be raised from the `DynView` module in py3.11.

```python
.../brainpy/_src/dynsys.py", line 809, in __init__
    if not isinstance(idx, collections.Iterable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by chaoming0625** [comment]
Thanks for the report. While, we do not recommend to use ``hh[None, 1:]``. This function may encounter strange  bugs.
