### ISSUE TITLE
Question on DSRunner

### ISSUE THREAD

**Issue by allLives** [brainpy/BrainPy#688]
Hi, I wrote a simple customized neuron, and did the simulation with DSRunner, but the result is strange and not right. So I did the simulation with update function manually in for loop, and the result is correct now. Could you please help me to find out why this happen, thank you very much!
![1](https://github.com/user-attachments/assets/2e3ba4c7-893b-4224-b177-7dd249bb3e51)
![2](https://github.com/user-attachments/assets/68e445ba-85ae-4c31-8896-8f1bccc13005)
![3](https://github.com/user-attachments/assets/4d33297f-9013-44d3-ab98-d3182a89f095)

**Comment by Routhleck** [comment]
Thank you for your question! Could you please share the source code using a [GitHub Gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) or a markdown code block (by adding ``` before and after your code)? This will make it easier for me to assist you.

**Comment by allLives** [comment]
> Thank you for your question! Could you please share the source code using a [GitHub Gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) or a markdown code block (by adding ``` before and after your code)? This will make it easier for me to assist you.

OK, thank you. Here's my code:
'''
import brainpy as bp
import brainpy.math as bm
import numpy as np
import matplotlib.pyplot as plt

class CustomNeuron(bp.dyn.NeuDyn):
    def __init__(self, size, tau, theta=1., r=2., **kwargs):
        super(CustomNeuron, self).__init__(size, **kwargs)
        self.tau = tau
        self.theta = theta
        self.r = r
        self.u = bm.Variable(bm.zeros(size))
        self.q = bm.Variable(bm.zeros(size))
        self.z = bm.Variable(bm.zeros(size))
        self.integral = bp.odeint(self.dqdt, method='rk4')

    def dqdt(self, q, t, u):
        return (u - q) / self.tau

    def update(self, _t=None, _dt=None):
        _t = _t if _t is not None else bp.share['t']
        _dt = _dt if _dt is not None else bp.share['dt']
        new_q = self.integral(self.q.value, _t, self.u.value, dt=_dt)
        z = (bm.exp((new_q - self.theta) * self.r)) / (1 + bm.exp((new_q - self.theta) * self.r))
        self.q.value = new_q
        self.z.value = z

# 创建模型实例
neus = CustomNeuron(1, tau=10, theta=0.5, r=2.)

# 创建输入信号
current1, duration = bp.inputs.section_input(values=[0., 0.02, 0.],
                                             durations=[100, 300, 500],
                                             return_length=True,
                                             dt=0.1)

# 初始化仿真时间和状态记录
times = np.arange(0, duration, 0.1)
q_values_manual = []

# 手动仿真
_t = 0
_dt = 0.1
for i in range(len(times)):
    neus.u.value = current1[i,None]
    neus.update(_t=_t, _dt=_dt)
    q_values_manual.append(neus.q.value)
    _t += _dt

# 将状态记录转换为NumPy数组
q_values_manual = np.array(q_values_manual).flatten()

# 使用DSRunner进行仿真
runner = bp.DSRunner(neus,
                     inputs=[('u', current1, 'iter')],
                     monitors=['q', 'z'])

# 运行仿真
runner.run(duration)

# 绘制结果
plt.plot(times, q_values_manual, label='Manual Simulation')
plt.plot(runner.mon.ts, runner.mon.q, label='DSRunner Simulation')
plt.xlabel('Time')
plt.ylabel('q Value')
plt.legend()
plt.title('Comparison of Manual and DSRunner Simulations')
plt.grid(True)
plt.show()

# Mannual Simulation Only
plt.plot(times, q_values_manual, label='Manual Simulation')
# plt.plot(runner.mon.ts, runner.mon.q, label='DSRunner Simulation')
plt.xlabel('Time')
plt.ylabel('q Value')
plt.legend()
plt.title('Comparison of Manual and DSRunner Simulations')
plt.grid(True)
plt.show()
'''

**Comment by allLives** [comment]
> Thank you for your question! Could you please share the source code using a [GitHub Gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) or a markdown code block (by adding ``` before and after your code)? This will make it easier for me to assist you.

OK, thank you. Here's my code:
'''
import brainpy as bp
import brainpy.math as bm
import numpy as np
import matplotlib.pyplot as plt

class CustomNeuron(bp.dyn.NeuDyn):
    def __init__(self, size, tau, theta=1., r=2., **kwargs):
        super(CustomNeuron, self).__init__(size, **kwargs)
        self.tau = tau
        self.theta = theta
        self.r = r
        self.u = bm.Variable(bm.zeros(size))
        self.q = bm.Variable(bm.zeros(size))
        self.z = bm.Variable(bm.zeros(size))
        self.integral = bp.odeint(self.dqdt, method='rk4')

    def dqdt(self, q, t, u):
        return (u - q) / self.tau

    def update(self, _t=None, _dt=None):
        _t = _t if _t is not None else bp.share['t']
        _dt = _dt if _dt is not None else bp.share['dt']
        new_q = self.integral(self.q.value, _t, self.u.value, dt=_dt)
        z = (bm.exp((new_q - self.theta) * self.r)) / (1 + bm.exp((new_q - self.theta) * self.r))
        self.q.value = new_q
        self.z.value = z


neus = CustomNeuron(1, tau=10, theta=0.5, r=2.)
current1, duration = bp.inputs.section_input(values=[0., 0.02, 0.],
                                             durations=[100, 300, 500],
                                             return_length=True,
                                             dt=0.1)
times = np.arange(0, duration, 0.1)
q_values_manual = []
_t = 0
_dt = 0.1
for i in range(len(times)):
    neus.u.value = current1[i,None]
    neus.update(_t=_t, _dt=_dt)
    q_values_manual.append(neus.q.value)
    _t += _dt
q_values_manual = np.array(q_values_manual).flatten()

runner = bp.DSRunner(neus,
                     inputs=[('u', current1, 'iter')],
                     monitors=['q', 'z'])
runner.run(duration)


plt.plot(times, q_values_manual, label='Manual Simulation')
plt.plot(runner.mon.ts, runner.mon.q, label='DSRunner Simulation')
plt.xlabel('Time')
plt.ylabel('q Value')
plt.legend()
plt.title('Comparison of Manual and DSRunner Simulations')
plt.grid(True)
plt.show()

plt.plot(times, q_values_manual, label='Manual Simulation')
plt.xlabel('Time')
plt.ylabel('q Value')
plt.legend()
plt.title('Comparison of Manual and DSRunner Simulations')
plt.grid(True)
plt.show()
'''

**Comment by allLives** [comment]
> Thank you for your question! Could you please share the source code using a [GitHub Gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) or a markdown code block (by adding ``` before and after your code)? This will make it easier for me to assist you.

OK, thank you. Here's my code: [https://gist.github.com/allLives/0b27f14dc64fa3a51c46b5b2e099ec4a](url)

**Comment by Routhleck** [comment]
We recommend using the method outlined in [this tutorial](https://brainpy.readthedocs.io/en/latest/tutorial_building/build_network_models.html#defining-a-network-with-customized-update-function) to customize the inputs received by the `update` function.

Here is the correct code: 
```python
import brainpy as bp
import brainpy.math as bm
import numpy as np
import matplotlib.pyplot as plt

class CustomNeuron(bp.dyn.NeuDyn):
    def __init__(self, size, tau, theta=1., r=2., **kwargs):
        super(CustomNeuron, self).__init__(size, **kwargs)
        self.tau = tau
        self.theta = theta
        self.r = r
        self.u = bm.Variable(bm.zeros(size))
        self.q = bm.Variable(bm.zeros(size))
        self.z = bm.Variable(bm.zeros(size))
        self.integral = bp.odeint(self.dqdt, method='rk4')

    def dqdt(self, q, t, u):
        return (u - q) / self.tau

    def update(self, u_input, _t=None, _dt=None):
        self.u.value = u_input
        _t = bp.share['t'] if _t is None else _t
        _dt = bp.share['dt'] if _dt is None else _dt
        new_q = self.integral(self.q.value, _t, self.u.value, dt=_dt)
        z = (bm.exp((new_q - self.theta) * self.r)) / (1 + bm.exp((new_q - self.theta) * self.r))
        self.q.value = new_q
        self.z.value = z
        return self.q, self.z

# Create a model instance
neus = CustomNeuron(1, tau=10, theta=0.5, r=2.)

# Create input signal
current1, duration = bp.inputs.section_input(values=[0., 0.02, 0.],
                                             durations=[100, 300, 500],
                                             return_length=True,
                                             dt=0.1)
current1 = current1.reshape(current1.shape[0], 1)  # Ensure correct shape for input

# Initialize simulation time and state records
times = np.arange(0, duration, 0.1)
q_values_manual = []

# Manual simulation
_t = 0
_dt = 0.1
for i in range(len(times)):
    neus.update(current1[i], _t, _dt)
    q_values_manual.append(neus.q.value)
    _t += _dt

# Convert state records to NumPy array
q_values_manual = np.array(q_values_manual).flatten()

# Using DSRunner for simulation
neus = CustomNeuron(1, tau=10, theta=0.5, r=2.)
runner = bp.DSRunner(neus, monitors=['q', 'z'])

# Run simulation
runner.run(inputs=current1)
mon_q = np.asarray(runner.mon['q'])

# Plot results
plt.plot(times, q_values_manual, label='Manual Simulation')
plt.plot(runner.mon['ts'], runner.mon['q'], label='DSRunner Simulation')
plt.xlabel('Time')
plt.ylabel('q Value')
plt.legend()
plt.title('Comparison of Manual and DSRunner Simulations')
plt.grid(True)
plt.show()
```

**Comment by allLives** [comment]
@Routhleck That works, thank you very much!
